### ISSUE TITLE
Social media images still use old background

### ISSUE THREAD

**Issue by potiuk** [softwareguru/airflowsummit-website#18]
Seems that when you are sharing the summit page, the thumbnails are still showing the old white background + colorful Airlfow logo. It could just be delay in refreshing it, but I just wanted to raise it in case it needs an update

**Comment by pedrogk** [comment]
The website metadata points to the new image since Friday, but it could be that in a specific network and for a specific url it still has the old image cached. Could you please say in which url and social media this happened so we can check it out?

For future reference, you can verify card info/image shown:
* https://cards-dev.twitter.com/validator
* https://developers.facebook.com/tools/debug
* https://www.linkedin.com/post-inspector/inspect

**Comment by potiuk** [comment]
Twitter and Facebook are OK.

LinkedIn is still with the old image (at least preview)
![Screenshot 2020-02-25 at 00 17 34](https://user-images.githubusercontent.com/595491/75199862-82bd1f80-5764-11ea-9ead-3fa681866f0a.png)

**Comment by pedrogk** [comment]
I see that. Even though the Linkedin post inspector shows the new image, when you actually try to post it still shows the old image. Let me do a deploy using a different filename for the image to see if that makes something. If not, we will have to wait for it to be updated (about 7 days from what I read).

**Comment by pedrogk** [comment]
This is fixed. We changed the name of the image to keep the old one from being cached.
